job: Multiple_OD600_growth_rates_ingestion_by_pattern

description: "Multiple experiments parsing, fitting, and plotting OD values. \n There three averaging methods: \n \t 1- No replicate (no averaging). \n \t 2- Replicate: average OD values among replicates. \n \t 3- Post replicate: average growth rate values among replicates."

variables:

  variant:
    - name: no_replicates
      pipeline: growth_rate_fit_pipeline
    - name: replicates
      pipeline: growth_rate_replicates_fit_pipeline
    - name: post_replicates
      pipeline: growth_rate_post_replicates_fit_pipeline

defaults:
  data_root: $WILL_PROVIDE$
  raw_data_file_name_pattern: $WILL_PROVIDE$
  metadata_file_name_pattern: $WILL_PROVIDE$

stages:
  #------------------------------------------------
  #------------------------------------------------
  - name: growth_rate_fit_pipeline
    pipeline_yaml: growth_rates_pipeline.yaml
    pipeline: "{variant.pipeline}"
  #------------------------------------------------
    fanout:
      type: patterns
      data_dir: "{data_root}"
      raw_pattern: "{raw_data_file_name_pattern}"
      meta_pattern: "{metadata_file_name_pattern}"
  #------------------------------------------------
    input_sources: 
       raw_data: "{data_root}\\{item.raw}" # raw_pattern in fanout
       meta_data: "{data_root}\\{item.meta}" # meta_pattern in fanout
  #------------------------------------------------
    # Passing values into the pipeline
    process_arg_mapping:
        df_predict_modified_gompertz: 
            save_plot_data: False
    
  #------------------------------------------------
    output_dir: "{data_root}\\processed\\{variant.name}\\{item.stem}"
  #------------------------------------------------